import Head from 'next/head'
import Header from '../blocks/Header'
import Footer from '../blocks/Footer'

function Layout({children}) {
  return (
    <>
      <Head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Scarlet Albornoz Portfolio</title>
      </Head>

      <Header/>

      <main className='color-light grow-1 container p-none d-flex fd-col jc-center'>
        {children}
      </main>
      <Footer/>
    </>
  )
}

export default Layout